"""Synthetic data generation and (optional) real-data loading."""

from __future__ import annotations

import logging
from pathlib import Path

import numpy as np
import pandas as pd

from .config import FraudConfig

logger = logging.getLogger(__name__)


def make_synthetic(
    n: int = 60_000,
    contamination: float = 0.0017,
    seed: int = 42,
) -> pd.DataFrame:
    """Generate a *clearly-labeled synthetic* fraud-detection dataset.

    Mimics the statistical shape of PCA-anonymized card-fraud data (28
    Gaussian components V1..V28, an Amount column, extreme class imbalance)
    WITHOUT copying any real transaction. Fraud class differs by a shifted,
    heavy-tailed subset of components, so supervised and unsupervised methods
    have something real to find - but every number produced from this mode is
    a property of the generator, NOT of real-world fraud. The study marks all
    such outputs accordingly.
    """
    rng = np.random.default_rng(seed)
    n_fraud = max(1, int(round(n * contamination)))
    n_legit = n - n_fraud

    d = 28
    # legitimate transactions: standard normal components + correlated amounts
    v_legit = rng.normal(0.0, 1.0, size=(n_legit, d))
    amount_legit = np.abs(rng.lognormal(mean=3.2, sigma=1.1, size=n_legit))
    y_legit = np.zeros(n_legit, dtype=int)

    # fraud: a few components shifted (the "signal"), but a documented
    # fraction of frauds is "stealth" (drawn from the legitimate
    # distribution) so that perfect detection is impossible - as in reality
    stealth = rng.uniform(size=n_fraud) < 0.15
    v_fraud = rng.normal(0.0, 1.0, size=(n_fraud, d))
    # deterministic core signal dims (V1..V3) + seeded random extras, so the
    # generator is reproducible AND always findable by feature-name
    signal_dims = [0, 1, 2, *rng.choice(range(3, d), size=4, replace=False).tolist()]
    for dim in signal_dims:
        v_fraud[:, dim] += rng.normal(1.7, 0.4)  # moderate location shift
    v_fraud[stealth] = rng.normal(0.0, 1.0, size=(int(stealth.sum()), d))
    v_fraud[:, 0] *= rng.uniform(1.8, 2.6, size=n_fraud)
    amount_fraud = np.abs(rng.lognormal(mean=4.4, sigma=1.4, size=n_fraud))
    y_fraud = np.ones(n_fraud, dtype=int)

    v = np.vstack([v_legit, v_fraud])
    amounts = np.concatenate([amount_legit, amount_fraud])
    y = np.concatenate([y_legit, y_fraud])
    order = rng.permutation(n)

    frame = pd.DataFrame(v, columns=[f"V{i+1}" for i in range(d)])
    frame["Amount"] = amounts
    frame["Class"] = y
    frame = frame.iloc[order].reset_index(drop=True)
    if not 0 < frame["Class"].mean() < 0.05:
        raise ValueError("synthetic generator produced an implausible fraud rate")
    return frame


def load_data(config: FraudConfig) -> tuple[pd.DataFrame, str]:
    """Load the requested source; returns (frame, provenance_label)."""
    if config.source == "synthetic":
        frame = make_synthetic(config.n_synthetic, config.contamination, config.random_state)
        return frame, "synthetic (generated by this repository; NOT real transactions)"
    if config.source == "kaggle":
        path = Path(config.raw_dir) / "creditcard.csv"
        if not path.exists():
            raise FileNotFoundError(
                f"{path} not found. The ULB dataset is distributed via Kaggle "
                "(mlg-ulb/creditcardfraud); download it yourself with the Kaggle API "
                "or the website, place the CSV there, and rerun with --source kaggle. "
                "The repository never redistributes the data."
            )
        frame = pd.read_csv(path)
        required = {"Class", "Amount"}
        if not required.issubset(frame.columns):
            raise ValueError("kaggle CSV must contain Class and Amount columns")
        return frame, "real data: ULB Credit Card Fraud (Kaggle, PCA-anonymized)"
    raise ValueError(f"unknown source: {config.source}")
